version: "3.5"

services:
  selenium:
    container_name: selenium
    image: seleniarm/standalone-chrome:latest
    ports:
      - "4444:4444"
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    volumes:
      - /dev/shm:/dev/shm
    shm_size: "2gb"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail -X HEAD http://localhost:4444/wd/hub",
        ]
      interval: 2s
      timeout: 5s
      retries: 30
  integration:
    container_name: integration
    build: .
    depends_on:
      - selenium

networks:
  default:
    name: test-network
